# Apache server-status for PathoCore host reverse proxy.

ExtendedStatus On

<VirtualHost *:80>
    ServerName __SERVER_STATUS_SERVER_NAME__
    ServerAlias __SERVER_STATUS_ALIASES__

    <Location /server-status>
        SetHandler server-status
        Require ip __SERVER_STATUS_ALLOW_FROM__
    </Location>
</VirtualHost>
