ServerName localhost

<VirtualHost *:8080>
    ProxyPreserveHost On
    ProxyRequests Off
    AllowEncodedSlashes NoDecode

    ProxyPass /static/ !
    ProxyPass /documents/ !

    Alias /static/ "/var/www/pathocore-api/static/"
    <Directory "/var/www/pathocore-api/static/">
        Require all granted
    </Directory>

    Alias /documents/ "/var/www/pathocore-api/documents/"
    <Directory "/var/www/pathocore-api/documents/">
        Require all granted
    </Directory>

    ProxyPass /api/ http://pathocore_api:8000/
    ProxyPassReverse /api/ http://pathocore_api:8000/

    ProxyPass /realms/ http://keycloak:8080/realms/
    ProxyPassReverse /realms/ http://keycloak:8080/realms/

    ProxyPass /resources/ http://keycloak:8080/resources/
    ProxyPassReverse /resources/ http://keycloak:8080/resources/

    ProxyPass /admin/ http://keycloak:8080/admin/
    ProxyPassReverse /admin/ http://keycloak:8080/admin/

    ProxyPass / http://pathocore_web:3000/
    ProxyPassReverse / http://pathocore_web:3000/
</VirtualHost>
