#!/usr/bin/env bash
set -euo pipefail

: "${SMTP_RELAY_HOST:?SMTP_RELAY_HOST is required}"

export SMTP_RELAY_PORT="${SMTP_RELAY_PORT:-25}"
export SMTP_RELAY_TLS_SECURITY_LEVEL="${SMTP_RELAY_TLS_SECURITY_LEVEL:-may}"
export SMTP_RELAY_MYHOSTNAME="${SMTP_RELAY_MYHOSTNAME:-pathocore-smtp-relay}"
export SMTP_RELAY_MYORIGIN="${SMTP_RELAY_MYORIGIN:-localhost}"
export SMTP_RELAY_MYDESTINATION="${SMTP_RELAY_MYDESTINATION:-localhost}"
export SMTP_RELAY_MYNETWORKS="${SMTP_RELAY_MYNETWORKS:-127.0.0.0/8 172.16.0.0/12 [::1]/128}"
export SMTP_RELAY_INET_INTERFACES="${SMTP_RELAY_INET_INTERFACES:-all}"
export SMTP_RELAY_INET_PROTOCOLS="${SMTP_RELAY_INET_PROTOCOLS:-ipv4}"
export SMTP_RELAY_TLS_CA_FILE="${SMTP_RELAY_TLS_CA_FILE:-/etc/ssl/certs/ca-certificates.crt}"

envsubst '$SMTP_RELAY_HOST $SMTP_RELAY_PORT $SMTP_RELAY_TLS_SECURITY_LEVEL $SMTP_RELAY_MYHOSTNAME $SMTP_RELAY_MYORIGIN $SMTP_RELAY_MYDESTINATION $SMTP_RELAY_MYNETWORKS $SMTP_RELAY_INET_INTERFACES $SMTP_RELAY_INET_PROTOCOLS $SMTP_RELAY_TLS_CA_FILE' \
    < /etc/postfix/main.cf.template > /etc/postfix/main.cf

postfix check

exec "$@"
